version: '2'
services:
  jhipsterreactnative-postgresql:
    image: postgres:11.4
    # volumes:
    #     - ~/volumes/jhipster/JhipsterReactNative/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=JhipsterReactNative
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
